import type { EnergyTestQuestion, EnergyTestSnapshot } from '@/entities/energy/model/types';

export const ENERGY_TEST_V1_ID = 'energy-test-v1';
export const ENERGY_TEST_V1_VERSION = 1;
export const ENERGY_TEST_V1_NAME = 'Energy Test v1';

const V1_QUESTIONS: EnergyTestQuestion[] = [
  {
    id: 'energy-q-physical_energy-v1',
    key: 'physical_energy',
    version: 1,
    textRu: 'Насколько ты сейчас физически чувствуешь себя наполненным энергией?',
    textEn: 'How physically energized do you feel right now?',
    minValue: 0,
    maxValue: 10,
    minLabelRu: 'Полностью истощён, хочется только отдыхать',
    minLabelEn: 'Completely drained, I only want to rest',
    midLabelRu: 'Обычное состояние, могу заниматься повседневными делами',
    midLabelEn: 'A usual state, I can handle everyday things',
    maxLabelRu: 'Очень много физической энергии',
    maxLabelEn: 'A lot of physical energy',
    reverseScoring: false,
    defaultWeight: 1,
    isActive: true,
    sortOrder: 1,
    weight: 1,
  },
  {
    id: 'energy-q-mental_clarity-v1',
    key: 'mental_clarity',
    version: 1,
    textRu: 'Насколько тебе сейчас легко сосредоточиться и удерживать внимание?',
    textEn: 'How easy is it for you to focus and keep your attention right now?',
    minValue: 0,
    maxValue: 10,
    minLabelRu: 'Очень трудно думать и концентрироваться',
    minLabelEn: 'It is very hard to think and concentrate',
    midLabelRu: 'Могу нормально сосредоточиться на простых задачах',
    midLabelEn: 'I can focus normally on simple tasks',
    maxLabelRu: 'Очень легко концентрируюсь, голова ясная',
    maxLabelEn: 'It is very easy to focus, my mind feels clear',
    reverseScoring: false,
    defaultWeight: 1,
    isActive: true,
    sortOrder: 2,
    weight: 1,
  },
  {
    id: 'energy-q-readiness_to_act-v1',
    key: 'readiness_to_act',
    version: 1,
    textRu: 'Насколько тебе сейчас хочется начать и выполнять какие-то действия?',
    textEn: 'How much do you feel like starting and doing something right now?',
    minValue: 0,
    maxValue: 10,
    minLabelRu: 'Совершенно нет желания что-либо делать',
    minLabelEn: 'I have no desire to do anything',
    midLabelRu: 'Готов делать необходимые дела без особого желания',
    midLabelEn: 'I can do what is needed, without much desire',
    maxLabelRu: 'Есть сильное желание действовать и что-то делать',
    maxLabelEn: 'I strongly want to act and do something',
    reverseScoring: false,
    defaultWeight: 1,
    isActive: true,
    sortOrder: 3,
    weight: 1,
  },
  {
    id: 'energy-q-inner_tension-v1',
    key: 'inner_tension',
    version: 1,
    textRu: 'Насколько ты сейчас чувствуешь внутреннее напряжение или перегруженность?',
    textEn: 'How much inner tension or overload do you feel right now?',
    minValue: 0,
    maxValue: 10,
    minLabelRu: 'Полностью спокоен, ничего не давит',
    minLabelEn: 'Completely calm, nothing is pressing on me',
    midLabelRu: 'Есть умеренное напряжение',
    midLabelEn: 'There is moderate tension',
    maxLabelRu: 'Сильно перегружен, трудно расслабиться',
    maxLabelEn: 'Heavily overloaded, it is hard to relax',
    reverseScoring: true,
    defaultWeight: 1,
    isActive: true,
    sortOrder: 4,
    weight: 1,
  },
  {
    id: 'energy-q-near_term_readiness-v1',
    key: 'near_term_readiness',
    version: 1,
    textRu: 'Если тебе сейчас понадобится заняться важным делом в течение ближайших 2–3 часов, насколько ты чувствуешь себя готовым к этому?',
    textEn: 'If you needed to work on something important in the next 2–3 hours, how ready do you feel?',
    minValue: 0,
    maxValue: 10,
    minLabelRu: 'Скорее всего, не справлюсь без отдыха',
    minLabelEn: 'I probably could not manage without rest',
    midLabelRu: 'Смогу, но потребуется усилие',
    midLabelEn: 'I could, but it would take effort',
    maxLabelRu: 'Чувствую себя полностью готовым',
    maxLabelEn: 'I feel fully ready',
    reverseScoring: false,
    defaultWeight: 1,
    isActive: true,
    sortOrder: 5,
    weight: 1,
  },
];

export function getDefaultEnergyTestSnapshot(): EnergyTestSnapshot {
  return {
    id: ENERGY_TEST_V1_ID,
    version: ENERGY_TEST_V1_VERSION,
    name: ENERGY_TEST_V1_NAME,
    isActive: true,
    questions: V1_QUESTIONS.map((question) => ({ ...question })),
  };
}
